### ISSUE TITLE
Remover wildcard imports do arquivo db

### ISSUE THREAD

**Issue by Yoshida-Eduardo** [TecProg-20181/T--amigosdopeixe#13]
## Comportamento esperado

Devem ser utilizados imports específicos

## *Comportamento atual

São utilizados wildcard imports ( from ... import *), o que é uma prática não recomendada. 

## **Critérios de Aceitação

- [x] Utilização de imports específicos
- [x] Não devem haver wildcard imports

**Comment by mateusvroriz** [comment]
Issue Done
